#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0 on Sun May 11 17:06:55 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((726, 250))
        self.SetTitle("Sfz to Decentsampler")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetToolTip("Add controls for effects to the DecentSampler file.")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sfz file:")
        sizer_2.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 7)

        self.text_ctrl_file = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_file.SetMinSize((600, 34))
        sizer_2.Add(self.text_ctrl_file, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.TOP, 5)

        self.button_1 = wx.Button(self.panel_1, wx.ID_ANY, "...")
        self.button_1.SetMinSize((45, 34))
        sizer_2.Add(self.button_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.TOP, 5)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Name output:")
        sizer_3.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 7)

        self.text_ctrl_name_output = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_name_output.SetMinSize((550, 34))
        sizer_3.Add(self.text_ctrl_name_output, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 3)

        self.button_2 = wx.Button(self.panel_1, wx.ID_ANY, "Run")
        self.button_2.SetToolTip("Generate individual DecentSampler file.")
        sizer_1.Add(self.button_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM | wx.TOP, 7)

        static_line_1 = wx.StaticLine(self.panel_1, wx.ID_ANY)
        sizer_1.Add(static_line_1, 0, wx.EXPAND, 0)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Folder to Scan:")
        sizer_4.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 7)

        self.text_ctrl_folder = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_folder.SetMinSize((550, 34))
        sizer_4.Add(self.text_ctrl_folder, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.TOP, 5)

        self.button_scan = wx.Button(self.panel_1, wx.ID_ANY, "...")
        self.button_scan.SetMinSize((45, 34))
        sizer_4.Add(self.button_scan, 0, wx.ALIGN_CENTER_VERTICAL | wx.TOP, 5)

        self.button_scan_folders = wx.Button(self.panel_1, wx.ID_ANY, "Scan")
        self.button_scan_folders.SetMinSize((85, 34))
        self.button_scan_folders.SetToolTip("Scan folder and subfolders and generates a DecentSampler file for each .szf file found. \n")
        sizer_1.Add(self.button_scan_folders, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM | wx.TOP, 7)

        static_line_2 = wx.StaticLine(self.panel_1, wx.ID_ANY)
        sizer_1.Add(static_line_2, 0, wx.EXPAND, 0)

        self.checkbox_effects = wx.CheckBox(self.panel_1, wx.ID_ANY, "Effects")
        self.checkbox_effects.SetValue(1)
        sizer_1.Add(self.checkbox_effects, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM | wx.TOP, 3)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.button_1.Bind(wx.EVT_BUTTON, self.select_file)
        self.button_2.Bind(wx.EVT_BUTTON, self.run)
        self.button_scan.Bind(wx.EVT_BUTTON, self.select_folder)
        self.button_scan_folders.Bind(wx.EVT_BUTTON, self.scan_folders)
        # end wxGlade

    def select_file(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'select_file' not implemented!")
        event.Skip()

    def run(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'run' not implemented!")
        event.Skip()

    def select_folder(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'select_folder' not implemented!")
        event.Skip()

    def scan_folders(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'scan_folders' not implemented!")
        event.Skip()

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
